package com.example.notify.service

import android.app.Notification
import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import android.util.Log
import com.example.notify.NotifyApplication
import com.example.notify.data.local.NotificationEntity
import java.util.concurrent.ConcurrentHashMap
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch

class NotificationCaptureService : NotificationListenerService() {
    private val serviceScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)
    private val recentByNotificationKey = ConcurrentHashMap<String, SeenNotification>()

    private val notificationRepository by lazy {
        (application as NotifyApplication).notificationRepository
    }

    private val settingsRepository by lazy {
        (application as NotifyApplication).settingsRepository
    }

    override fun onNotificationPosted(sbn: StatusBarNotification?) {
        if (sbn == null) return

        // Ignore notifications generated by this app to avoid capture->repost loops.
        if (sbn.packageName == packageName) return

        val notification = sbn.notification
        val extras = notification.extras

        val packageName = sbn.packageName.orEmpty()
        val appName = resolveAppName(packageName)
        val title = extras?.getCharSequence(Notification.EXTRA_TITLE)?.toString().orEmpty()
        val message = extras?.getCharSequence(Notification.EXTRA_TEXT)?.toString().orEmpty()
        val bigTextValue = extras?.getCharSequence(Notification.EXTRA_BIG_TEXT)?.toString()
        val bigText = bigTextValue?.takeIf { it.isNotBlank() && it != message }
        val timestamp = if (sbn.postTime > 0L) sbn.postTime else System.currentTimeMillis()

        val contentSignature = "$title|$message|${bigText.orEmpty()}"
        if (isDuplicateRecentPost(sbn.key, contentSignature, timestamp)) {
            Log.d(TAG, "Skipping duplicate notification update for key=${sbn.key}")
            return
        }

        serviceScope.launch {
            runCatching {
                notificationRepository.processCapturedNotification(
                    NotificationEntity(
                        appName = appName,
                        packageName = packageName,
                        title = title,
                        message = message,
                        bigText = bigText,
                        timestamp = timestamp
                    )
                )
            }.onFailure { error ->
                Log.e(TAG, "Failed to persist captured notification", error)
            }
        }

        if (settingsRepository.isAutoDismissEnabled()) {
            runCatching {
                cancelNotification(sbn.key)
            }.onFailure { error ->
                Log.w(TAG, "Could not remove notification from system tray", error)
            }
        }
    }

    override fun onDestroy() {
        super.onDestroy()
        serviceScope.cancel()
    }

    override fun onNotificationRemoved(sbn: StatusBarNotification?) {
        if (sbn?.key.isNullOrBlank()) return
        recentByNotificationKey.remove(sbn?.key)
    }

    private fun isDuplicateRecentPost(key: String, signature: String, timestamp: Long): Boolean {
        val previous = recentByNotificationKey[key]
        recentByNotificationKey[key] = SeenNotification(signature, timestamp)

        if (previous == null) return false
        val sameContent = previous.signature == signature
        val closeInTime = kotlin.math.abs(timestamp - previous.timestamp) <= DUPLICATE_WINDOW_MS
        return sameContent && closeInTime
    }

    private fun resolveAppName(packageName: String): String {
        if (packageName.isBlank()) return "Unknown app"
        return runCatching {
            val appInfo = packageManager.getApplicationInfo(packageName, 0)
            packageManager.getApplicationLabel(appInfo).toString()
        }.getOrElse { packageName }
    }

    companion object {
        private const val TAG = "NotificationCaptureSvc"
        private const val DUPLICATE_WINDOW_MS = 15_000L
    }

    private data class SeenNotification(
        val signature: String,
        val timestamp: Long
    )
}
